### PR TITLE
Port to Python 3 and pure python

### PR DESCRIPTION
**Pull request by oaxiom**
I ported to Py3, and converted the pyc to pure python for portability - it seems fast enough without the pyc. 

I got it running but I didn't test the install, I just hooked it onto the PATH and PYTHONPATH, and it produced the expected output and completed with no errors in my hands. Please consider merging. Python 2 seems basically defunct at this point.

Andrew Hutchins.

### CODE REVIEW

**Comment by AliciaSchep** [comment]
Hi @oaxiom -- Thanks for putting this together, I will definitely consider merging.  I'll need a bit of time to take a look through the changes & try out the install first though.

**Comment by AliciaSchep** [comment]
I'm going to merge this to a feature branch (py3) and try to update the setup.py and stuff like that to work.

**Comment by AliciaSchep** [comment]
@oaxiom thanks again for contributing this port to python 3 -- I made a few additions to your version so that some test examples would give same results as python 2 and so it could get installed via pip or setup.py.  Also just a note that it still contains some cython -- the multinomial_cov.py file is still in Cython (you hadn't converted that one --  I took a quick try at changing that one back to pure python too but it was a lot slower and I recall speed issues for that function being the impetus for cython back in the day.)  Have made a new PR at #96, but will first see if it can be made backwards compatible with python 2 before merging

**Comment by oaxiom** [comment]
Thanks for merging, tidying up and testing. NucleoATAC is pretty useful. 

I'll take a look at multinomial_cov.py if/when I get a chance.

**Pull request merged**
